"""
Casa Monarca SDK - Cryptography Module.

Provides BIP39 Spanish mnemonic generation, key derivation, P-256 ECDSA signing,
and signature verification, fully compatible with the frontend client.
"""

import hashlib
import secrets
import unicodedata
from typing import Dict, List, Union

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric import utils as asymmetric_utils
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed

from casa_monarca_sdk.exceptions import CryptographyError, ValidationError

# BIP39 Spanish custom wordlist (1309 words) used by Casa Monarca
WORDLIST: List[str] = [
    "ábaco",
    "abdomen",
    "abeja",
    "abierto",
    "abogado",
    "abono",
    "aborto",
    "abrazo",
    "abrir",
    "abuelo",
    "abuso",
    "acabar",
    "academia",
    "acceso",
    "acción",
    "aceite",
    "acelga",
    "acento",
    "aceptar",
    "ácido",
    "aclarar",
    "acné",
    "acoger",
    "acoso",
    "activo",
    "acto",
    "actuar",
    "acudir",
    "acuerdo",
    "acusar",
    "adicto",
    "admitir",
    "adoptar",
    "adorno",
    "aduana",
    "adulto",
    "aéreo",
    "afectar",
    "afición",
    "agencia",
    "agitar",
    "agonía",
    "agosto",
    "agotar",
    "agrado",
    "agrio",
    "agua",
    "agudo",
    "águila",
    "aguja",
    "ahogo",
    "ahorro",
    "aire",
    "aislar",
    "ajedrez",
    "ajeno",
    "ajuste",
    "alacrán",
    "alambre",
    "alarma",
    "alba",
    "álbum",
    "alcalde",
    "aldea",
    "alegre",
    "alejar",
    "alerta",
    "aleta",
    "alfiler",
    "alga",
    "algodón",
    "aliento",
    "alivio",
    "alma",
    "almeja",
    "almíbar",
    "altar",
    "alteza",
    "altivo",
    "alto",
    "altura",
    "alumno",
    "alzar",
    "amable",
    "amante",
    "amapola",
    "amargo",
    "amasar",
    "ámbar",
    "ámbito",
    "ambos",
    "ambulancia",
    "amigo",
    "amnistía",
    "amor",
    "amparo",
    "amplio",
    "ancho",
    "anciano",
    "ancla",
    "andar",
    "andén",
    "anemia",
    "ángulo",
    "anhelo",
    "ánimo",
    "anís",
    "anotar",
    "antena",
    "antiguo",
    "antojo",
    "anual",
    "anular",
    "anuncio",
    "añadir",
    "añejo",
    "año",
    "apagar",
    "aparato",
    "apetito",
    "apio",
    "aplicar",
    "apodo",
    "aporte",
    "apoyo",
    "aprender",
    "aprobar",
    "apuesta",
    "apuro",
    "arado",
    "araña",
    "arar",
    "árbitro",
    "árbol",
    "arbusto",
    "archivo",
    "arco",
    "arder",
    "ardilla",
    "arduo",
    "área",
    "árido",
    "aries",
    "armonía",
    "arnés",
    "aroma",
    "arpa",
    "arpón",
    "arrancar",
    "arrastre",
    "arreglo",
    "arroz",
    "arruga",
    "arte",
    "artista",
    "asa",
    "asado",
    "asalto",
    "ascenso",
    "asegurar",
    "aseo",
    "asesor",
    "asiento",
    "asilo",
    "asistir",
    "asno",
    "asombro",
    "áspero",
    "astilla",
    "astro",
    "astuto",
    "asumir",
    "asunto",
    "atajo",
    "ataque",
    "atar",
    "atento",
    "ateo",
    "ático",
    "atleta",
    "átomo",
    "atraer",
    "atroz",
    "atún",
    "audaz",
    "auge",
    "aula",
    "aumento",
    "ausente",
    "autor",
    "aval",
    "avance",
    "avaro",
    "ave",
    "avellana",
    "avena",
    "avión",
    "aviso",
    "ayer",
    "ayuda",
    "ayuno",
    "azafrán",
    "azar",
    "azote",
    "azúcar",
    "azufre",
    "azul",
    "baba",
    "balcón",
    "balde",
    "bambú",
    "banco",
    "banda",
    "baño",
    "barba",
    "barco",
    "barniz",
    "barro",
    "báscula",
    "bastón",
    "basura",
    "batería",
    "batir",
    "bautismo",
    "bazar",
    "bebé",
    "béisbol",
    "belleza",
    "besar",
    "beso",
    "bestia",
    "bicho",
    "bien",
    "bingo",
    "blanco",
    "blindar",
    "bloque",
    "bobina",
    "boca",
    "bocina",
    "boda",
    "bodega",
    "boina",
    "bola",
    "bolsillo",
    "bomba",
    "bondad",
    "borrar",
    "bosque",
    "botín",
    "bóveda",
    "bravo",
    "brazo",
    "brecha",
    "breve",
    "brillo",
    "brindar",
    "brisa",
    "broca",
    "broma",
    "bronce",
    "brote",
    "brujo",
    "brusco",
    "bruto",
    "buceo",
    "budín",
    "bueno",
    "buey",
    "búfalo",
    "bufanda",
    "búho",
    "buitre",
    "bulto",
    "buque",
    "burla",
    "buscar",
    "butaca",
    "buzón",
    "cabal",
    "caballo",
    "caber",
    "cabina",
    "cable",
    "cacao",
    "cadáver",
    "cadena",
    "caer",
    "café",
    "caída",
    "caimán",
    "caja",
    "cajón",
    "cal",
    "calamar",
    "calcio",
    "caldo",
    "calidad",
    "calle",
    "calma",
    "calor",
    "calvo",
    "cama",
    "cambio",
    "camello",
    "camino",
    "campo",
    "cáncer",
    "candil",
    "cantidad",
    "cañón",
    "caoba",
    "caos",
    "capaz",
    "capitán",
    "capote",
    "captar",
    "capucha",
    "cara",
    "carbón",
    "cárcel",
    "carga",
    "carnaval",
    "caro",
    "carpa",
    "carro",
    "carta",
    "casa",
    "casco",
    "caspa",
    "castor",
    "caudal",
    "causa",
    "cazo",
    "cebolla",
    "cerebro",
    "cereza",
    "cerrar",
    "certeza",
    "cesped",
    "cetro",
    "chico",
    "chiste",
    "chivo",
    "choque",
    "ciclo",
    "ciego",
    "cielo",
    "ciento",
    "cierto",
    "cifra",
    "cigarro",
    "cima",
    "cinco",
    "cinta",
    "circo",
    "ciruela",
    "cisne",
    "cita",
    "ciudad",
    "clamor",
    "clan",
    "claro",
    "clavar",
    "cobro",
    "coche",
    "cocina",
    "código",
    "codo",
    "cofre",
    "coger",
    "cohete",
    "cojín",
    "col",
    "cola",
    "colapso",
    "colcha",
    "cólera",
    "colgar",
    "colina",
    "collar",
    "colmo",
    "columna",
    "combate",
    "cometer",
    "cómodo",
    "compra",
    "común",
    "conejo",
    "conjunto",
    "cono",
    "copa",
    "copia",
    "coque",
    "corbata",
    "cordón",
    "corona",
    "correr",
    "coser",
    "cosmos",
    "costa",
    "cremoso",
    "cría",
    "crisis",
    "crónica",
    "cruce",
    "cruel",
    "cuadro",
    "cuarto",
    "cuatro",
    "cubo",
    "cuello",
    "cueva",
    "cuidar",
    "culpa",
    "cultivo",
    "cumbre",
    "cúpula",
    "cupón",
    "curar",
    "dardo",
    "dato",
    "deber",
    "débil",
    "década",
    "decir",
    "dedo",
    "defensa",
    "definir",
    "dejar",
    "delfín",
    "demora",
    "dental",
    "deporte",
    "derecho",
    "derrota",
    "desayuno",
    "deseo",
    "destino",
    "diablo",
    "diadema",
    "dibujo",
    "diente",
    "dieta",
    "diez",
    "difícil",
    "digno",
    "dinero",
    "disco",
    "diseño",
    "disfraz",
    "diva",
    "divino",
    "doble",
    "dolor",
    "dominio",
    "dragón",
    "droga",
    "ducha",
    "duda",
    "duelo",
    "dueño",
    "dulce",
    "dúo",
    "duque",
    "durar",
    "dureza",
    "duro",
    "ébano",
    "eclipse",
    "edad",
    "edición",
    "edificio",
    "editor",
    "educar",
    "efectivo",
    "efecto",
    "eficaz",
    "eje",
    "ejemplo",
    "elefante",
    "elegir",
    "elixir",
    "elogio",
    "eludir",
    "embudo",
    "emitir",
    "emoción",
    "empate",
    "empresa",
    "enano",
    "encanto",
    "enemigo",
    "enfado",
    "enfermo",
    "engaño",
    "enigma",
    "enorme",
    "enredo",
    "ensayo",
    "entrar",
    "envío",
    "época",
    "equipo",
    "erial",
    "error",
    "escena",
    "esfera",
    "espejo",
    "esposa",
    "establo",
    "estación",
    "estado",
    "estancia",
    "estar",
    "estatua",
    "estudio",
    "estufa",
    "etapa",
    "eterno",
    "ético",
    "Europa",
    "evacuar",
    "evitar",
    "exacto",
    "examen",
    "exceso",
    "exhibir",
    "exilio",
    "éxito",
    "experto",
    "exponer",
    "éxtasis",
    "extremo",
    "fábrica",
    "fácil",
    "factor",
    "faja",
    "falda",
    "fallo",
    "falso",
    "faltar",
    "fama",
    "familia",
    "faraón",
    "faro",
    "fase",
    "fatiga",
    "favor",
    "fax",
    "febrero",
    "feliz",
    "felpudo",
    "femenino",
    "fémur",
    "fenómeno",
    "feo",
    "feria",
    "feroz",
    "fértil",
    "fervor",
    "festín",
    "fiable",
    "fianza",
    "fiar",
    "fibra",
    "ficción",
    "ficha",
    "fideo",
    "fiebre",
    "fiero",
    "fiesta",
    "figura",
    "fijar",
    "fijo",
    "fila",
    "filete",
    "filme",
    "finca",
    "fingir",
    "finito",
    "firma",
    "flaco",
    "flauta",
    "flecha",
    "flor",
    "flota",
    "fluir",
    "flujo",
    "flúor",
    "fobia",
    "foca",
    "fogón",
    "folleto",
    "fondo",
    "fontana",
    "footing",
    "foráneo",
    "forcejo",
    "forja",
    "forma",
    "forro",
    "fortuna",
    "forzar",
    "fosa",
    "foto",
    "fracaso",
    "frágil",
    "franja",
    "frase",
    "fraude",
    "freír",
    "freno",
    "fresa",
    "frío",
    "frito",
    "frontal",
    "frotar",
    "fructosa",
    "fuego",
    "fuente",
    "fuerza",
    "fuga",
    "fugaz",
    "fulgor",
    "función",
    "furgón",
    "furia",
    "fusible",
    "fútbol",
    "futuro",
    "gacela",
    "gafas",
    "galería",
    "gallo",
    "gamba",
    "ganar",
    "gancho",
    "ganga",
    "garaje",
    "garza",
    "gasolina",
    "gastar",
    "gemelo",
    "general",
    "género",
    "genio",
    "germen",
    "gesto",
    "gigante",
    "gimnasio",
    "girasol",
    "glaciar",
    "globo",
    "glorioso",
    "glosario",
    "gobierno",
    "golfo",
    "goloso",
    "golpe",
    "gordo",
    "gorila",
    "gorro",
    "gota",
    "goteo",
    "gozar",
    "gracia",
    "grado",
    "gráfico",
    "gramo",
    "grande",
    "granja",
    "grano",
    "grasa",
    "gratis",
    "grave",
    "grieta",
    "grito",
    "grosor",
    "grúa",
    "grupo",
    "guante",
    "guapo",
    "guarda",
    "guerra",
    "guía",
    "guiño",
    "guion",
    "guiso",
    "guitarra",
    "gusano",
    "gustar",
    "haber",
    "hábil",
    "hablar",
    "hacer",
    "hallar",
    "hamaca",
    "harina",
    "hastío",
    "hazaña",
    "hebilla",
    "hecho",
    "helado",
    "herida",
    "hermano",
    "hielo",
    "hierro",
    "hígado",
    "hilo",
    "historia",
    "hogar",
    "hoguera",
    "hoja",
    "hombre",
    "hongo",
    "hora",
    "horno",
    "húmedo",
    "hundir",
    "huracán",
    "iceberg",
    "ideal",
    "ídolo",
    "iglesia",
    "ignorar",
    "igual",
    "imagen",
    "imán",
    "imitar",
    "impacto",
    "incapaz",
    "índice",
    "inerte",
    "infiel",
    "informe",
    "inmenso",
    "innato",
    "inodoro",
    "insecto",
    "instante",
    "interés",
    "íntimo",
    "intriga",
    "inútil",
    "invierno",
    "inyectar",
    "isla",
    "jabalí",
    "jabón",
    "jamón",
    "jarabe",
    "jardín",
    "jarra",
    "jaula",
    "jazmín",
    "jefe",
    "jeringa",
    "jinete",
    "jornada",
    "jorobado",
    "joven",
    "joya",
    "juerga",
    "juicio",
    "junco",
    "jungla",
    "junta",
    "jurar",
    "justo",
    "juzgar",
    "lacra",
    "ladera",
    "ladrillo",
    "lagarto",
    "lágrima",
    "laguna",
    "lamento",
    "lámina",
    "lance",
    "langosta",
    "lanza",
    "lápiz",
    "largo",
    "larva",
    "lástima",
    "latido",
    "látigo",
    "lavado",
    "lazo",
    "leal",
    "lección",
    "legión",
    "lejano",
    "lengua",
    "lento",
    "leña",
    "leopardo",
    "lesión",
    "letal",
    "libre",
    "libro",
    "licor",
    "límite",
    "limón",
    "limpiar",
    "lince",
    "lío",
    "listo",
    "literal",
    "litro",
    "llama",
    "lluvia",
    "lobo",
    "lodo",
    "lógica",
    "lograr",
    "loro",
    "lucha",
    "lugar",
    "lujo",
    "luna",
    "luto",
    "luz",
    "madera",
    "madre",
    "magia",
    "maldad",
    "maleta",
    "mambo",
    "manar",
    "mancha",
    "mandato",
    "manera",
    "mañana",
    "mapa",
    "máquina",
    "marca",
    "marcha",
    "marea",
    "margen",
    "mármol",
    "masa",
    "máscara",
    "materia",
    "mayor",
    "mecer",
    "medalla",
    "médico",
    "medio",
    "mejor",
    "melena",
    "melon",
    "memoria",
    "menor",
    "mensaje",
    "mente",
    "menú",
    "mercado",
    "mérito",
    "meta",
    "método",
    "mezcla",
    "miedo",
    "miel",
    "miembro",
    "miga",
    "milagro",
    "militar",
    "millón",
    "mínimo",
    "minuto",
    "mirar",
    "misa",
    "mismo",
    "mitad",
    "moderno",
    "mojar",
    "molde",
    "moler",
    "molino",
    "momento",
    "monje",
    "moño",
    "moral",
    "morder",
    "moreno",
    "morir",
    "morro",
    "morsa",
    "mosca",
    "mostrar",
    "motivo",
    "mover",
    "móvil",
    "mozo",
    "muchos",
    "mueble",
    "muela",
    "muerte",
    "muestra",
    "mugre",
    "mujer",
    "mulo",
    "multa",
    "mundo",
    "muñeca",
    "muralla",
    "murciélago",
    "músculo",
    "muslo",
    "nácar",
    "nación",
    "nadar",
    "naipe",
    "naranja",
    "nariz",
    "néctar",
    "negar",
    "negocio",
    "negro",
    "neón",
    "nervio",
    "nido",
    "niebla",
    "nieto",
    "ninguno",
    "nítido",
    "nivel",
    "noche",
    "nómada",
    "nórdico",
    "norma",
    "notable",
    "novato",
    "novela",
    "néctar",
    "nudillo",
    "nudo",
    "nuera",
    "objeto",
    "obra",
    "océano",
    "odiar",
    "odio",
    "oeste",
    "ofensa",
    "oferta",
    "oficio",
    "oído",
    "ojival",
    "ola",
    "olfato",
    "olivo",
    "olla",
    "ombligo",
    "ópera",
    "optar",
    "oráculo",
    "orden",
    "oreja",
    "órgano",
    "orgullo",
    "orilla",
    "orinar",
    "ornamento",
    "oro",
    "orquesta",
    "oruga",
    "osadía",
    "oscuro",
    "osito",
    "óvalo",
    "oveja",
    "óxido",
    "ozono",
    "pacto",
    "pagar",
    "página",
    "pájaro",
    "palco",
    "paleta",
    "paloma",
    "palpar",
    "panceta",
    "pánico",
    "pantera",
    "pañuelo",
    "papel",
    "papilla",
    "pareja",
    "párpado",
    "párrafo",
    "pasar",
    "patata",
    "patria",
    "pausa",
    "peca",
    "pedal",
    "peinado",
    "peldaño",
    "película",
    "peligro",
    "pelota",
    "pena",
    "pensar",
    "peón",
    "percal",
    "perder",
    "pereza",
    "pétalo",
    "picaro",
    "picor",
    "pieza",
    "pimienta",
    "pincel",
    "piñón",
    "pirata",
    "pisada",
    "pistón",
    "plaga",
    "plano",
    "plástico",
    "plato",
    "playa",
    "plaza",
    "pleito",
    "plomo",
    "pluma",
    "población",
    "poco",
    "poder",
    "podio",
    "poesía",
    "polvo",
    "pomada",
    "pómulo",
    "poner",
    "portal",
    "posada",
    "poyete",
    "precio",
    "premio",
    "prensa",
    "presa",
    "prima",
    "primo",
    "prisa",
    "privar",
    "proa",
    "probar",
    "pronto",
    "propina",
    "próximo",
    "prueba",
    "público",
    "puchero",
    "pulpo",
    "pulso",
    "puntada",
    "punto",
    "puñal",
    "pupila",
    "puré",
    "quedar",
    "queja",
    "quemar",
    "querer",
    "queso",
    "quince",
    "quitar",
    "rábano",
    "rabia",
    "ración",
    "raíz",
    "rama",
    "rampa",
    "rápido",
    "rapto",
    "rasgo",
    "rastra",
    "rato",
    "rayo",
    "raza",
    "razón",
    "rebelde",
    "recibo",
    "recta",
    "recurso",
    "redil",
    "redondo",
    "reflejo",
    "refrán",
    "regalo",
    "regla",
    "reino",
    "relleno",
    "remar",
    "rendir",
    "repaso",
    "reptil",
    "rescatar",
    "resina",
    "respeto",
    "retablo",
    "retrato",
    "reunir",
    "revista",
    "rico",
    "riesgo",
    "rígido",
    "rigor",
    "rincón",
    "riñón",
    "río",
    "riqueza",
    "risa",
    "ritmo",
    "rival",
    "rojizo",
    "romano",
    "romper",
    "ropa",
    "rostro",
    "rubio",
    "rugir",
    "ruido",
    "ruina",
    "ruleta",
    "rumor",
    "sabio",
    "sable",
    "sacar",
    "sagrado",
    "saltar",
    "salud",
    "sano",
    "sapo",
    "saqueo",
    "sátira",
    "sauce",
    "sección",
    "seda",
    "seguir",
    "sello",
    "selva",
    "semana",
    "sendero",
    "sensación",
    "señal",
    "serie",
    "serón",
    "siesta",
    "siglo",
    "signo",
    "sílaba",
    "silbar",
    "símbolo",
    "sirena",
    "sistema",
    "sitio",
    "soborno",
    "socio",
    "sodio",
    "soga",
    "soja",
    "solapa",
    "solar",
    "sólido",
    "sombra",
    "sondeo",
    "sonido",
    "soplo",
    "soportar",
    "sordo",
    "sorpresa",
    "sorteo",
    "sótano",
    "suave",
    "subir",
    "suceder",
    "sudor",
    "suerte",
    "suma",
    "superar",
    "sutil",
    "tabaco",
    "tacto",
    "tajo",
    "taller",
    "tambor",
    "tapa",
    "tarea",
    "tarjeta",
    "tarro",
    "taza",
    "tejado",
    "teja",
    "tela",
    "teléfono",
    "telón",
    "templo",
    "tendón",
    "tenso",
    "teoría",
    "terapia",
    "ternura",
    "terror",
    "tesoro",
    "tiempo",
    "timón",
    "tío",
    "típico",
    "título",
    "tiza",
    "tocar",
    "todo",
    "toldo",
    "tomar",
    "tónico",
    "torno",
    "torpe",
    "tos",
    "tosco",
    "tóxico",
    "trabajo",
    "traer",
    "tráfico",
    "trago",
    "traición",
    "traje",
    "tramo",
    "trance",
    "trapo",
    "través",
    "trébol",
    "tregua",
    "tribu",
    "trigo",
    "tripa",
    "triste",
    "triunfo",
    "trompa",
    "tronco",
    "trotar",
    "trozo",
    "truco",
    "trueno",
    "tubería",
    "túnel",
    "turno",
    "tutela",
    "úlcera",
    "umbral",
    "unidad",
    "unir",
    "urano",
    "urbano",
    "útil",
    "uva",
    "vacío",
    "vacuna",
    "vago",
    "vapor",
    "varón",
    "vecino",
    "vejez",
    "vena",
    "vencer",
    "venda",
    "veneno",
    "ventaja",
    "verano",
    "verdad",
    "vereda",
    "verso",
    "vértice",
    "vía",
    "viaje",
    "vicio",
    "vidrio",
    "vigor",
    "villa",
    "vínculo",
    "viola",
    "virus",
    "visor",
    "víspera",
    "vivir",
    "volcán",
    "volumen",
    "volver",
    "voraz",
    "votar",
    "vuelta",
    "yate",
    "yema",
    "yerno",
    "yeso",
    "yoga",
    "yugo",
    "zafiro",
    "zanja",
    "zapato",
    "zarza",
    "zona",
    "zorro",
    "zumo",
    "zurdo",
]


def sin_acentos(s: str) -> str:
    """Removes accents and normalizes a string to lowercase.

    Args:
        s (str): The string to normalize.

    Returns:
        str: Normalized lowercase string without accents.
    """
    s_norm = unicodedata.normalize("NFD", s.lower())
    return "".join(c for c in s_norm if unicodedata.category(c) != "Mn")


# Pre-normalized wordlist for high-performance lookups
WORDLIST_NORM: List[str] = [sin_acentos(w) for w in WORDLIST]


def generar_mnemonic() -> str:
    """Generates a cryptographically secure 12-word mnemonic.

    Uses rejection sampling to avoid modulo bias, matching the frontend client.

    Returns:
        str: A space-separated string of 12 Spanish words, normalized without accents.
    """
    size = len(WORDLIST)
    indices = []
    limit = (0x10000 // size) * size
    while len(indices) < 12:
        v = secrets.randbits(16)
        if v < limit:
            indices.append(v % size)
    return " ".join(sin_acentos(WORDLIST[i]) for i in indices)


def validar_mnemonic(mnemonic: str) -> bool:
    """Validates a mnemonic phrase structure and membership.

    Checks if the phrase has exactly 12 words and all of them exist in the wordlist.

    Args:
        mnemonic (str): Space-separated mnemonic phrase.

    Returns:
        bool: True if valid, False otherwise.
    """
    words = mnemonic.strip().split()
    if len(words) != 12:
        return False
    return all(sin_acentos(w) in WORDLIST_NORM for w in words)


def mnemonic_to_seed(mnemonic: str) -> bytes:
    """Converts a 12-word mnemonic into a 64-byte seed.

    Uses PBKDF2-HMAC-SHA512 with 'mnemonic' as salt, 2048 iterations.

    Args:
        mnemonic (str): 12-word mnemonic phrase.

    Returns:
        bytes: 64-byte derived seed.

    Raises:
        ValidationError: If the mnemonic is invalid.
    """
    if not validar_mnemonic(mnemonic):
        raise ValidationError(
            "Mnemonic inválido: debe contener 12 palabras del diccionario."
        )

    words = mnemonic.strip().split()
    normalized_words = [sin_acentos(w) for w in words]
    normalized_mnemonic = " ".join(normalized_words)

    seed = hashlib.pbkdf2_hmac(
        hash_name="sha512",
        password=normalized_mnemonic.encode("utf-8"),
        salt=b"mnemonic",
        iterations=2048,
        dklen=64,
    )
    return seed


def derivar_llaves(mnemonic: str) -> Dict[str, Union[bytes, str]]:
    """Derives the ECDSA P-256 key pair from a mnemonic phrase.

    The first 32 bytes of the derived BIP39 seed are used as the private key.

    Args:
        mnemonic (str): 12-word mnemonic phrase.

    Returns:
        dict: A dictionary containing:
            - 'private_key_bytes' (bytes): 32-byte private key.
            - 'public_key_bytes' (bytes): 33-byte compressed public key.
            - 'public_key_hex' (str): 66-character compressed public key hex string.

    Raises:
        CryptographyError: If derivation fails.
    """
    try:
        seed = mnemonic_to_seed(mnemonic)
        private_key_bytes = seed[:32]

        private_key = ec.derive_private_key(
            int.from_bytes(private_key_bytes, byteorder="big"), ec.SECP256R1()
        )

        public_key = private_key.public_key()
        public_key_bytes = public_key.public_bytes(
            encoding=serialization.Encoding.X962,
            format=serialization.PublicFormat.CompressedPoint,
        )

        return {
            "private_key_bytes": private_key_bytes,
            "public_key_bytes": public_key_bytes,
            "public_key_hex": public_key_bytes.hex(),
        }
    except ValidationError as e:
        raise e
    except Exception as e:
        raise CryptographyError(f"Error al derivar llaves: {e}")


def firmar_hash(hash_hex: str, private_key_bytes: bytes) -> str:
    """Signs a SHA-256 hash using the derived private key.

    Args:
        hash_hex (str): 64-character SHA-256 hash hex string.
        private_key_bytes (bytes): 32-byte private key.

    Returns:
        str: 128-character compact signature hex string (r + s).

    Raises:
        ValidationError: If the hash format is incorrect.
        CryptographyError: If signing fails.
    """
    try:
        hash_bytes = bytes.fromhex(hash_hex)
        if len(hash_bytes) != 32:
            raise ValidationError("El hash debe tener exactamente 32 bytes.")

        private_key = ec.derive_private_key(
            int.from_bytes(private_key_bytes, byteorder="big"), ec.SECP256R1()
        )

        der_signature = private_key.sign(
            hash_bytes, ec.ECDSA(Prehashed(hashes.SHA256()))
        )

        r, s = asymmetric_utils.decode_dss_signature(der_signature)
        compact_signature = r.to_bytes(32, "big") + s.to_bytes(32, "big")
        return compact_signature.hex()
    except ValueError:
        raise ValidationError("El hash debe ser una cadena hexadecimal válida.")
    except ValidationError as e:
        raise e
    except Exception as e:
        raise CryptographyError(f"Error al firmar el hash: {e}")


def verificar_firma_local(
    hash_hex: str, signature_hex: str, public_key_hex: str
) -> bool:
    """Verifies an ECDSA P-256 signature locally.

    Args:
        hash_hex (str): 64-character SHA-256 hash hex string.
        signature_hex (str): 128-character compact signature hex string.
        public_key_hex (str): 66-character compressed public key hex string.

    Returns:
        bool: True if signature is valid, False otherwise.
    """
    try:
        hash_bytes = bytes.fromhex(hash_hex)
        sig_bytes = bytes.fromhex(signature_hex)
        pub_bytes = bytes.fromhex(public_key_hex)

        if (
            len(hash_bytes) != 32
            or len(sig_bytes) != 64
            or len(pub_bytes) not in (33, 65)
        ):
            return False

        r = int.from_bytes(sig_bytes[:32], "big")
        s = int.from_bytes(sig_bytes[32:], "big")
        der_signature = asymmetric_utils.encode_dss_signature(r, s)

        public_key = ec.EllipticCurvePublicKey.from_encoded_point(
            ec.SECP256R1(), pub_bytes
        )

        public_key.verify(
            der_signature, hash_bytes, ec.ECDSA(Prehashed(hashes.SHA256()))
        )
        return True
    except Exception:
        return False
